//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorialsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rating()
        {
            this.Rate = 0;
        }
    
        public int Id { get; set; }
        public int Rate { get; set; }
        public int TutorialId { get; set; }
        public string AspNetUserId { get; set; }
        public System.DateTime RatedOn { get; set; }
    
        public virtual Tutorial Tutorial { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
